---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.9
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: subtitles
          hajimari.io/appName: Bazarr
          # nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
        hosts:
          - host: bazarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - bazarr.${SECRET_DOMAIN}
    env:
      TZ: Europe/Brussels
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 172.16.1.6
            path: /volume1/Media
        mountPath: /media
    resources:
      requests:
        memory: 512Mi
        cpu: 150m
      limits:
        memory: 1024Mi
