---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudnative-pg
spec:
  retentionPolicy: 30d
  configuration:
    wal:
      compression: bzip2
      maxParallel: 8
    destinationPath: s3://cloudnative-pg/
    endpointURL: http://minio.home.${SECRET_ROOT_DOMAIN}:9000
    serverName: postgres16-2
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: cloudnative-pg
        key: MINIO_SECRET_KEY
