---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.0.2512
    env:
      TZ: Europe/Brussels
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: music-box
          hajimari.io/appName: Lidarr
        hosts:
          - host: lidarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - lidarr.${SECRET_DOMAIN}
      api:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: lidarr.${SECRET_DOMAIN}
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - lidarr.${SECRET_DOMAIN}
    podSecurityContext:
      supplementalGroups:
        - 100
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.0.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 172.16.1.6
            path: /volume1/Media
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
