---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: kube-system
spec:
  releaseName: dex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: coredns
      namespace: kube-system
  values:
    image:
      repository: dexidp/dex
      tag: v2.30.0
    env:
      KUBERNETES_POD_NAMESPACE: kube-system
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dex.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.${SECRET_DOMAIN}
    config:
      issuer: https://dex.${SECRET_DOMAIN}

      storage:
        type: kubernetes
        config:
          inCluster: true
      web:
        http: 0.0.0.0:5556

      frontend:
        theme: coreos
        issuer: cardboardboxhome
        issuerUrl: https://${SECRET_DOMAIN}
        logoUrl: https://cardboardbox.be/box.svg

      expiry:
        signingKeys: 6h
        idTokens: 24h

      logger:
        level: debug
        format: json

      oauth2:
        responseTypes: [code, token, id_token]
        skipApprovalScreen: true

      connectors:
        # GitHub configure 'OAuth Apps' -> 'New OAuth App', add callback URL
        # https://github.com/settings/developers
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirectURI: https://dex.${SECRET_DOMAIN}/callback
            # 'orgs' can be used to map groups from Github
            # https://github.com/coreos/dex/blob/master/Documentation/connectors/github.md
            orgs:
              - name: cardboardboxhome

      staticClients:
        - id: grafana
          name: grafana
          secret: ${GRAFANA_CLIENT_SECRET}
          redirectURIs:
            - https://grafana.${SECRET_DOMAIN}/login/generic_oauth

        - id: oauth2-proxy
          name: oauth2-proxy
          secret: ${OAUTH2_PROXY_CLIENT_SECRET}
          redirectURIs:
            - https://auth.${SECRET_DOMAIN}/oauth2/callback

    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 250Mi
