---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter-edgerouter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: snmp-exporter-edgerouter
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - --config.file=/config/snmp.yaml
    extraConfigmapMounts:
      - name: snmp-exporter-edgerouter
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-edgerouter
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: edgerouter
          enabled: true
          module:
            - ubiquiti_edgemax
          target: 172.16.1.1
      path: /snmp
      # interval: 60s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
