---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SECRET_CERTMANAGER_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
        webhook:
          solverName: linode
          groupName: acme.${SECRET_DOMAIN}
