---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cert-manager-webhook-linode-charts
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: master
  url: https://github.com/slicen/cert-manager-webhook-linode
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/
