---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns
  - descheduler
  - dex
  - etcd
  - external-dns
  - intel-gpu-plugin
  - kube-cleanup-operator
  - kured
  - metrics-server
  - node-feature-discovery
  - node-problem-detector
  - oauth2-proxy
