---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-problem-detector
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 5m
  values:
    metrics:
      serviceMonitor:
        enabled: true
