---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gaps-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block
