---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:CzKeFtGgOYdpBtMCqHg=,iv:JYQmF0kjXF+l2JMOImyNgBhju+0rtdjlvCLxkxORtfQ=,tag:6eO+a+/b2mxO7ITtQEfLdA==,type:str]
  SECRET_ROOT_DOMAIN: ENC[AES256_GCM,data:xBY8g34oQZVe4pGdsGQo,iv:tWnMTqGQJEdnIoEPpvRYP6t3nxyEccEgO2GZTma4kN4=,tag:GVyB2xb8jEI9sCJF67WIfQ==,type:str]
  SECRET_EMAIL: ENC[AES256_GCM,data:mSTZjbJSRnrJvN8NGY5DprPBStwRt8Dm0/fhC+tc,iv:ExafO6mWwdomKZUtVQX7ajV5A/rUfbHxbiqthcWRgi4=,tag:P5g69IKmIcMnaCAGnw2ksw==,type:str]
  SECRET_LONGHORN_BACKUPTARGET: ENC[AES256_GCM,data:gBS8jli5RWp4AHdK6mR9HyqiGWPFBOTq1mVlsgXfADe/8m3HrtNzifKvVvM=,iv:bnvTuryk1enVWk2PYdlRGurPb0CJHw1RmzppsIzKEYc=,tag:fhK5q7J00KHP/XbTpdbcnQ==,type:str]
  GITHUB_CLIENT_ID: ENC[AES256_GCM,data:PXayYPXGubOS0G6/qZPjyIfqPS4=,iv:quYWHduY4ET45H5yNDhD7KPZsRy1r/VB1jr7HoxWj8o=,tag:SCxc0sdN6cRwvCMT5CE0Mw==,type:str]
  GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:OsRP19jzK9lS3a6YA3vC/5NtCKgLEXFYcQBuQHiO48GjZDb8rcDh+g==,iv:skjzyyMBuLaPFNfMDsg8BvKpTPTn75/keKrEPUkw6PA=,tag:l/E90tpluhy/bdrwQzMzIQ==,type:str]
  GRAFANA_PASSWORD: ENC[AES256_GCM,data:Sq80bYq+Kh6ofK8oMZN3,iv:GY/GRE5debAbRMsmxT9gl9FBQo7K1wK20F6NMhADHI4=,tag:1mOS9AiFhIBjhwv/yMXZ6Q==,type:str]
  GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:N1s+QrpfKOg0BnL8IZgzaeaNBcQmr5QrnAzBuPNmAYg=,iv:IJIyzIf/OoU6vQtFmSmCTq96CjumHoldDjm0v3Our60=,tag:ugOfUoQzli/Err2mYMmlGg==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:eQEXj8gAhSpqYkHev7D92Ig8/c9ehjy1vEg2bIRVkXY=,iv:+PP8L3nV1BA0Vu4GHQoipg7NS00LRrLCprBAgCMAADM=,tag:c4qy8Xkdq40YiglhYVcnpQ==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:CyJ5NDwHLo7l63jSZAQ7LFBDaLRJpAr9cyeLqNP0qbE=,iv:srdIKgfOTQzHGLyOgHjd0azq2o0zwnhpxM+764x1ruc=,tag:wUzBvoji2MhRPgPFqA9qiw==,type:str]
  SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:nG42X17ffALLFdQNLRDUDzDA,iv:4NJ2NCXU4nbpKkgQUnqlSQOVqFeFB3yewAKYkXho/xg=,tag:wfKQ/RxchnTsZiZBiZ4V4A==,type:str]
  SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:cjUSoVWmLOmZFvc0xjIgFl2KhycApnsqTJmrH36DjXu6hEoXn515dvrl8FMCl45NE+VwAySJAN22EXQ=,iv:c4uu0VSk1plm2TOHtXsRrnbiiD2wrWheGyC+g80xyv4=,tag:3xy8csbI6dXZ6c7wuaVDSQ==,type:str]
  SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:sGMCk4ND8nTvPtcbQPL07f1M,iv:qg6Ak9qs3bHQ+JCDpDskhZJMf51eafkm25dKHFkHu2U=,tag:c73C1+7aPaCKmFL8R2mIPg==,type:str]
  SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:3eGcxfH1cTdF3jt81T9MDuaF0mMRHiuiYABGqkvhPm7rbFkCHuFpVEa8/TZ8W6s5q74XZFnFp1ILPDe28pSSy5Bty/83AVEaLLhTsTMP+kD0gfvZzbiLW7XqYU2HMO7h7lVS8OKZq9EU+PjQKmlFeoG7uXrHD5ubBGlQAe3P,iv:tTBuBw8sdmtqHK2YeXdffi5XbCom36pO/86CSwYAe/s=,tag:105lrWThgETcn8poJzXNQw==,type:str]
  SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:KhBpunUP6ErwnA31GpNeDM3chw8VrRiqdOeiZF4+pxnXklVaQr2HCnUP/3Qmj5pFkp3m1tAfV6M7pecsi2hfTevDHeJ5dHxrtCfgQiCxUA37lN8jxlzyPpiCRfWObuw93padGtxhGfy2AZ+fih4EXVE5Ow7z31F+dVfZ2uLd51BIPGdeYRoBlAtUJ1s/gi6yNz/CtePGWGjMhhLZaZqMxVRGi9Jg0pMAbg0odg/940xGMIzi7v0s0kVn5mHnLzMBMn7JuJopEzZcwl7J,iv:jJ4dRRLjVTKImBtDdG20Vc99pZ5Q8vA0XXRkmAIZ0Kg=,tag:+OoEgfHAUCauozJNR88rqA==,type:str]
  VELERO_MINIO_URL: ENC[AES256_GCM,data:tvrAEOs+tQJvngej0jQUS6JDf216FSE=,iv:JIWdLVB9v+sRbxN3qkFYJ4BM9xoiaKSPaTh6Rh84BSM=,tag:FGYqjEr13qTQZy7BrvNJsw==,type:str]
  MONICA_APP_KEY: ENC[AES256_GCM,data:l6hEDLpAlZUbMEPigYwCGs8dfjCIIcpeEsI0NEL88Fj/u3BXNQlkBqotepQ2Sci0AFMK,iv:6alwhxAGBLgdMiO8K8stOc8YaPrEyXZ64Rh6YwAdKkA=,tag:M8OKVTsQ98Be9DNFDGFtAQ==,type:str]
  MONICA_DB_PASSWORD: ENC[AES256_GCM,data:djQaOSh2N5iMN/WKR2BAE+xd+qoYH+ptIGerYE7nsljbdU4UDc35kr5ZiO5pCT+A,iv:1g9ukBAx42FW2wc2Y4j/7aDvw6IuCp14t753jOGvV/o=,tag:M/wkl0WuhqQsFbPh/cUdzQ==,type:str]
  MONICA_DB_ROOTPASSWORD: ENC[AES256_GCM,data:lvOSHjN48eOPXOgfmihhnQFcjLvbRHeKw+X/ZvmJ0HEujQ3n6NVIJeKrYTQ7qUem,iv:UztGc1GWMho+QJzPmvamD4BsAt+BI1F0tWjeEQIXuAQ=,tag:+mmi+20LHpkySuuGkH3pGA==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:y0lpu0vjcJ3d3hc2O3bsOfw7iKqMX6XIliW4TNCfGoH9I7+wLr8XWImYuCEyiIJmZnE=,iv:+vRbU2U6kMuZdNDiInPM1o3iBY/43BNw5CbGr1O7YxM=,tag:S00T2YmptkRSNUuT31Pksg==,type:str]
  AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:mvADVJ5Qy3YxN60owwOwZkPMazx38zanVnwy9TO4jYLuZy6l9tiav/HklIbuTA1haWM=,iv:NgYWB+FEEW8WGB2wILAfbQoB0zUHKte/f1F43UpzkEE=,tag:jzAiOCFjZHNu9YuUfb0lEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wkeqj9ce5t24ec5u4zst942q8y2xstg8g9shjfqrsw5kpl6yl9nscc9jpe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMCsvNUpDZVpmaTF4bHVp
        b0pjSU10bkFWeDFVRy8ycVVTelRJdGZ6SjBrCjVUaGpsTEo3anRGVkw3MWVES0Nq
        SCtYcUQ0STQ5M21tWUlZcWllbUtXVEUKLS0tIElWdFNOeThiTUtyWDFWZFpjdVZ4
        TkE4ZjlJcm9tak80ZFR5Nk42SWIyTXcK7bD1L49zg9tpeniwdVoVDoIpkauZNX9U
        0xJL/FV2cz92Ip+Gl6IOyYE3iVLmfDptGYloy3dcQWE7ACwRAvPZvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-04-25T17:36:35Z'
  mac: ENC[AES256_GCM,data:GuP7J/cNTFPWiFQG0Ax/MWLnKWcA9PR2U/tWpj7yEb5r2c3wg1HdbF9eUZ5GH9swyMn29ar/HaF5IqZEsJC7TpvTmhNmeKjz+tcmTf1c9H0s3DvZ0c3w1TNsKyeIgwi6kRM7PYSHh89qGF0PQwRXwGfIcdTeIiIHfzYNUnyX/y8=,iv:5Ys2hwbJuafKzsF/L7iaJN3jM3rxVSgebLkVe7J3Mc8=,tag:QrXA7Hg/g9EAdoNLxYIEyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.2
