---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: default
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: monica-mariadb
  values:
    image:
      repository: monica
      tag: 3.7.0-apache
    env:
      APP_KEY: ${MONICA_APP_KEY}
      APP_URL: https://monica.${SECRET_DOMAIN}
      APP_ENV: production
      DB_HOST: monica-mariadb.default.svc
      DB_DATABASE: monica
      DB_USERNAME: monica
      DB_PASSWORD: ${MONICA_DB_PASSWORD}
      DEFAULT_MAX_STORAGE_SIZE: 4096
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: contacts
          hajimari.io/appName: Monica
        hosts:
          - host: monica.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - monica.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 250Mi
    mariadb:
      enabled: false
