---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: default
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: monica
      tag: 3.5.0-apache
    env:
      APP_URL: https://monica.${SECRET_DOMAIN}
      APP_ENV: production
      DB_HOST: monica-mariadb
      DB_DATABASE: monica
      DB_USERNAME: monica
      DEFAULT_MAX_STORAGE_SIZE: 4096
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: contacts
          hajimari.io/appName: Monica
        hosts:
          - host: monica.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - monica.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 250Mi
    mariadb:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: 10.6.5-debian-10-r46
      primary:
        persistence:
          enabled: true
          existingClaim: monica-mariadb
      auth:
        database: monica
        username: monica
