---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica-mariadb
  namespace: default
spec:
  releaseName: monica-mariadb
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 10.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 10.6.5-debian-10-r46
    primary:
      persistence:
        enabled: true
        existingClaim: monica-mariadb
    auth:
      database: monica
      username: monica
      password: ${MONICA_DB_PASSWORD}
      rootPassword: ${MONICA_DB_ROOTPASSWORD}
