---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  removeOSDsIfOutAndSafeToRemove: false
  mon:
    count: 3
    allowMultiplePerNode: false
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  crashCollector:
    disable: false
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  resources:
    mon:
      requests:
        cpu: 35m
        memory: 800Mi
      limits:
        memory: 1024Mi
    osd:
      requests:
        cpu: 35m
        memory: 2048Mi
      limits:
        memory: 4096Mi
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: '1'
    nodes:
      - name: big-kube-01
        devices:
          - name: sda
      - name: nuc-kube-01
        devices:
          - name: sdb
      - name: nuc-kube-02
        devices:
          - name: sdb
      - name: nuc-kube-03
        devices:
          - name: sdb
      - name: nuc-kube-04
        devices:
          - name: sdb
