---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataLocality: best-effort
      defaultDataPath: /mnt/longhorn/
      createDefaultDiskLabeledNodes: true
      backupTarget: ${SECRET_LONGHORN_BACKUPTARGET}
      storageMinimalAvailablePercentage: '10'
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: 'true'
        hajimari.io/icon: database
        hajimari.io/appName: Longhorn
        nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
