---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-linode
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/cert-manager-webhook-linode
      version: v0.2.0
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-linode-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: slicen/cert-manager-webhook-linode
      tag: v0.2.0
    api:
      groupName: acme.${SECRET_DOMAIN}
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: cert-manager-webhook-linode
              namespace: cert-manager
            spec:
              template:
                spec:
                  containers:
                    - name: cert-manager-webhook-linode
                      args:
                        - --tls-cert-file=/tls/tls.crt
                        - --tls-private-key-file=/tls/tls.key
