---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 30.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  timeout: 20m
  values:
    defaultRules:
      create: true
      rules:
        kubeApiserver: false
    prometheusOperator:
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
          slack_api_url: ${SECRET_ALERT_MANAGER_DISCORD_WEBHOOK}
        receivers:
          - name: 'null'
          - name: discord
            slack_configs:
              - channel: '#prometheus'
                icon_url: https://avatars3.githubusercontent.com/u/3380462
                username: Prometheus
                send_resolved: true
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}{{ .CommonLabels.alertname }}{{ end }}
                text: >-
                  {{ range .Alerts -}}
                    **Alert:** {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                  **Description:** {{ if ne .Annotations.description ""}}{{ .Annotations.description }}{{else}}N/A{{ end }}

                  **Details:**
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
        route:
          group_by: [alertname, job]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 6h
          receiver: discord
          routes:
            - receiver: 'null'
              match_re:
                alertname: Watchdog|etcdHighNumberOfFailedGRPCRequests
            - receiver: discord
              match_re:
                severity: critical
              continue: true
        inhibit_rules:
          - source_match:
              severity: critical
            target_match:
              severity: warning
            equal: [alertname, namespace]
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: alert-circle
          hajimari.io/appName: Alert-manager
        hosts:
          - alert-manager.${SECRET_DOMAIN}
        tls:
          - hosts:
              - alert-manager.${SECRET_DOMAIN}
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              resources:
                requests:
                  storage: 1Gi
    nodeExporter:
      serviceMonitor:
        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
    grafana:
      enabled: false
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
      endpoints:
        - 172.17.2.1
        - 172.17.2.2
        - 172.17.2.3
      service:
        enabled: true
        port: 10257
        targetPort: 10257
      serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
    kubeScheduler:
      enabled: true
      endpoints:
        - 172.17.2.1
        - 172.17.2.2
        - 172.17.2.3
    kubeProxy:
      enabled: true
      endpoints:
        - 172.17.2.1
        - 172.17.2.2
        - 172.17.2.3
    kubeEtcd:
      enabled: true
      endpoints:
        - 172.17.2.1
        - 172.17.2.2
        - 172.17.2.3
      service:
        enabled: true
        port: 2381
        targetPort: 2381
    kubelet:
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
    prometheus:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: torch
          hajimari.io/appName: Prometheus
        hosts:
          - prometheus.${SECRET_DOMAIN}
        tls:
          - hosts:
              - prometheus.${SECRET_DOMAIN}
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      prometheusSpec:
        ruleSelector: {}
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        retention: 168h
        enableAdminAPI: true
        walCompression: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: feature.node.kubernetes.io/cpu-cpuid.AVX
                      operator: In
                      values:
                        - 'true'
        thanos:
          image: quay.io/thanos/thanos:v0.24.0
          version: v0.22.0
          objectStorageConfig:
            name: thanos-objstore-secret
            key: objstore.yml
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              resources:
                requests:
                  storage: 50Gi
        additionalScrapeConfigs:
          - job_name: node-exporter
            honor_timestamps: true
            static_configs:
              - targets:
                  - 172.16.1.10:9100
