---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - lidarr
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - sonarr
  - tautulli
