---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 4.5.14
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    eula:
      accept: true
      company: cardboardbox
      email: woll0r@@users.noreply.github.com
    global:
      persistence:
        storageClass: rook-ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      class: nginx
      host: k10.${SECRET_DOMAIN}
      urlPath: k10
      hosts:
        - k10.${SECRET_DOMAIN}
      tls:
        enabled: true
        secretName: ${SECRET_DOMAIN//./-}-tls
      annotations:
        hajimari.io/enable: 'true'
        hajimari.io/icon: backup-restore
        hajimari.io/appName: Kasten K10
        external-dns.alpha.kubernetes.io/target: k8s-tunnel.${SECRET_ROOT_DOMAIN}
    grafana:
      enabled: false
