---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: source-controller
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: helm-controller
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              memory: 2Gi
