---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.6
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
  - name: dex
    namespace: kube-system
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.1.3
    replicaCount: 2
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - "auth.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "auth.${SECRET_DOMAIN}"
    config:
      clientID: "oauth2-proxy"
      clientSecret: "${OAUTH2_PROXY_CLIENT_SECRET}"
      cookieSecret: "${OAUTH2_PROXY_COOKIE_SECRET}"
    extraArgs:
      provider: oidc
      oidc-issuer-url: "https://dex.${SECRET_DOMAIN}"
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: ".${SECRET_DOMAIN}"
      whitelist-domain: ".${SECRET_DOMAIN}"