---
apiVersion: v1
kind: Secret
metadata:
  name: botkube-communications
  namespace: monitoring
type: Opaque
stringData:
  comm_config.yaml:
    communications:
      discord:
        enabled: ENC[AES256_GCM,data:FPSbsA==,iv:k2lne9GlaFd8aIeH1tLg3n7dN2H1Vw88DaeDxoCwzyM=,tag:rcNprfUS/bfGpc/VjICOWg==,type:bool]
        token: ENC[AES256_GCM,data:9r80zXiAC0aQBuqr1ODo/fRci7P6OKeRe1yoKm+kFKE+2rn5pAKqAQlS3926K771dpXzpOMsO7ZisW8=,iv:5yQ3yHBOsQsWTSdJMaxSTYXB9ggJJS59TpkK5z84T3U=,tag:EC6+Qf5k1EVxupPvFi2urA==,type:str]
        botid: ENC[AES256_GCM,data:dzv6uyI4f32fZ8pyrlbjiaSa,iv:quT7aULTESu5qMs+WW+oQOfL2dzmpVc/FrGVoovG8Ew=,tag:ajVaSXa4QSd/xZe2xkjl5w==,type:str]
        channel: ENC[AES256_GCM,data:zMA+QXzzr/nOcA7RZbEyYrkE,iv:N/P3ktffYL/Jjur0wTOSmZiZrsWwsyyKYXfxUbDtVzM=,tag:gDIG6h3fa8ivkuMD+ACHPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2021-09-12T04:44:30Z'
  mac: ENC[AES256_GCM,data:w+EqZ5wpFlt+QjYf7HNnUG9/HPLdj2k17UxGwQDITcybnCJpGLlCz18+9fcMOSNISEyK0tlmgH5fiADPAs5qzgSKi8wwuKymeqc4p62ZHUHNLeCvBqE9Z+GVBSogNF5aSFuW9IIo40hTDmmeNoKLQbQVoZjnNg7+7nCdn86dr74=,iv:fm2Aug9F0C8Zg4+EH/hBr8jTGVHL7DL0/HoQwGTw/Pw=,tag:LFd4R+efphc6s2DvH1SEUw==,type:str]
  pgp:
    - created_at: '2021-09-12T04:44:30Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA5YRaKofaz9CARAAjETmE0kiIQwihddNIkWGCNLDSlP70gDcJe6TUAOOpG0f
        bEMKciQ3dmesuSF1YH5IExSDcO3uz+wpHRQmm4nsTz64SFgCmfnk2Gj6ksnpLnJN
        kADSxp2HrOPxhc5wst6vv0YttzsHEuSYE8Bg02y69owr99BHiBbJzXWQ08lF/KEf
        06QYn/F5CC8d0eSSEIx6wDJF7+mVCXbnfxNv+JK1blnvelK3r3/vs9+3TA+JoPes
        LY/XpEAmTr80Y3tVB4/SpRmRoIeUmNcKZG5xortfrd3617qDDiAyqf+E30bOsGKr
        iY1AN2AdBc+pEsx09kqA5ssOtxJlvUg1+glBDQ3Gn/k45V2QnJGBzoY4yM01vvDZ
        UoQWlqKdffJOICBVPdz/l/vT+ZIqFfSaaFnMXFw7eEOLTFMS5xUUcWBYGFsQQ/ZK
        NQL1yVjCLMSb2KCBCbGxhxIuAh9v94haPNyBRcr6PKhdth9ymJbR0+snAYxhMiHy
        2BKFTI+ve9x5ll4twDAWELxrTX+P5u0qfdZwlC3LUWBjSID3UqvA21tgmgJQPJfe
        DyI+fdHoPAKz4ztWh70Q2ZaYnYhGmymvuSpguHm/FLFfyYk5o54Bs+Rr00l9MF4r
        QRKPDLTrBLZFubxw6Lew/SyS7xOeUREoLfNWoNi2EslrKibCnMerolQGQYJALmDS
        XgEEfrCPWPOU5Qc6xDAcmVMQ4EUudyYaGlkOC3RXpt8mj3VDMs4MTavJ/BQEoF7K
        C9zg9AaN71LbEO+7D3FBfKA94LaROUmCC2OKc6o+IVZO145i9QZqOr6YJiox6g0=
        =41B2
        -----END PGP MESSAGE-----
      fp: 9D499331E77AB71942B0BD98C18E05E9EFD35DA6
    - created_at: '2021-09-12T04:44:30Z'
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA6IKXLsgzTh+ARAALa5iAj9XBpP93ArKUE5BJ2lUpQNZ0OrNXi+g4ABgZzET
        0Ii4Oyq8juyX5EQpWtOPpECiX6ZrB17mOpAoFV88a/O8F62fw/O9w/bj6V7P1HbG
        EwfgYiZOKED0gWzriCLxuLfwgrrOv9Is/OJaFf43rmDZhGkk/yfGAo4mHZm5iV+G
        4vhbMw/dVl0oNFu79OaUSR31J1Rf/r82YU/Vwh18bgcav7/tjZcncB/4siE3vTkT
        jw0mLtH0pxC9n0jWWtrwfjzVKJeyOmRIQ+P21IDnAD4uaUaqUwcXt2PmE6y7duaY
        RS1BJmbg4VOAx9+w7gOamrKYyuZfoysJw8qGOKcXpLZNUvMpozY3RS6mejutgdc0
        9IMBPcdKMmjmeCk30fgoQscG2i2kYUiYV+qQTETOYST/FcWtRnzmVb9HohmDBg3r
        NyM4EQpoigBSip20WvZut7RjoMs30xuEvcRn62bYHMUoMznmv3Th3XdIE3ob9cdv
        3HsAhoU5blS6uSWipkqy7keK8fQm9VCiE9Q3trpoH1bUacrYMHmvinc1uA3l8CJH
        wDbevzbouQWBVBqPpR7sFJwYRIRWT6K1pqoK2Yxrxrt3t2Acm/v+aMQ1D0FNam/0
        z51Pg6ScxLQ13/h9iwWTSA8EAVG41jWEW0QwdZ5RNCpqnu95TH4AacfsbDlvN4TS
        5gFHSHLVm6s3PYOX7wFRZ5JdxHvDYWOiOxiAkibofYT4KJLQBeSjlFjQ3nbV1/hj
        UHAI8KUF2Ng91lpsK9wTb2rkgpSo/lCISxs4GYsP91ZXZuItvbFPAA==
        =z6cl
        -----END PGP MESSAGE-----
      fp: E2D99EA2EE98E4677A00C64769B7868093023FE3
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
