---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: Europe/Brussels
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - rook-ceph
          - kasten-io
          - media
          - monitoring
          - networking
      name: Wolfgang
      customApps:
        - name: Pi-hole
          url: https://pi-pihole.home.cardboardbox.be/
          icon: pi-hole
      groups:
        - name: Mail
          links:
            - name: Gmail
              url: https://gmail.com
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: hajimari.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - hajimari.${SECRET_DOMAIN}
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
